/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatorgume;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author leka
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public boolean okP = false;
    public boolean okT = false;
    public GUI() {
        initComponents();
        String[] prazan = {""};
        ComboBoxModel pp1e= new DefaultComboBoxModel( prazan );
        jComboBox1.setModel(pp1e);
        jComboBox1.setVisible(true);
        /////////////////////////////////////////////
        ComboBoxModel pp2e= new DefaultComboBoxModel(prazan);
        jComboBox2.setModel(pp2e);
        jComboBox2.setVisible(true);
        //////////////////////////////////////////////
        ComboBoxModel pp3e= new DefaultComboBoxModel(prazan);
        jComboBox3.setModel(pp3e);
        jComboBox3.setVisible(true);
        /////////////////////////////////////////////////
        ComboBoxModel pp4e= new DefaultComboBoxModel(prazan);
        brzinaSlovo.setModel(pp4e);
        brzinaSlovo.setVisible(true);
        /////////////////////////////////////////////////
        ComboBoxModel pp5e= new DefaultComboBoxModel(prazan);
        jComboBox5.setModel(pp5e);
        jComboBox5.setVisible(true);
        /////////////////////////////////////////////////
        ComboBoxModel pp6e= new DefaultComboBoxModel(prazan);
        jComboBox6.setModel(pp6e);
        jComboBox6.setVisible(true);
        /////////////////////////////////////////////////
        ComboBoxModel pp7e= new DefaultComboBoxModel(prazan);
        jComboBox7.setModel(pp7e);
        jComboBox7.setVisible(true);
        ////////////////////////////////////////////////////
        ComboBoxModel pp8e= new DefaultComboBoxModel(prazan);
        brzinaSlovoA.setModel(pp8e);
        brzinaSlovoA.setVisible(true);
        /////////////////////////////////////////////////////////
        ComboBoxModel pp9e= new DefaultComboBoxModel(prazan);
        indexNosivost.setModel(pp9e);
        indexNosivost.setVisible(true);
        //////////////////////////////////////////////////////////
        ComboBoxModel pp10e= new DefaultComboBoxModel(prazan);
        indexNosivostA.setModel(pp10e);
        indexNosivostA.setVisible(true);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        putnickaGuma = new javax.swing.JButton();
        teretnaGuma = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        brzinaSlovo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        precnikGume = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        obimGume = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        brojKM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        obrtaji = new javax.swing.JTextField();
        racunanje = new javax.swing.JButton();
        stvarnaV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        precnikGumeA = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        obimGumeA = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        brojKMA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        obrtajiA = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        razlikaH = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        brzinaSlovoA = new javax.swing.JComboBox<>();
        maxBrzina = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        razlikaBrzina = new javax.swing.JTextField();
        maxBrzinaA = new javax.swing.JTextField();
        indexNosivost = new javax.swing.JComboBox<>();
        indexNosivostA = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        razlikaNosivost = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        putnickaGuma.setText("Putnicko");
        putnickaGuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putnickaGumaActionPerformed(evt);
            }
        });

        teretnaGuma.setText("Teretno");
        teretnaGuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teretnaGumaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Precnik felne");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Sirina gume");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Visina gume");

        brzinaSlovo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        brzinaSlovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brzinaSlovoActionPerformed(evt);
            }
        });

        jLabel4.setText("Brzina");

        jLabel5.setText("Precnik gume");

        jLabel6.setText("Obim gume");

        jLabel7.setText("Broj obrtaja po KM/H");

        jLabel8.setText("Broj obrtaja u sekundi pri 100km/h");

        racunanje.setText("Racunanje");
        racunanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racunanjeActionPerformed(evt);
            }
        });

        jLabel9.setText("Stvarna brzina");

        jLabel10.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel10.setText("Originalno");

        jLabel11.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel11.setText("Alternativno");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Sirina gume");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setText("Visina gume");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Precnik felne");

        jLabel15.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel15.setText("Originalna");

        jLabel16.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel16.setText("Alternativna");

        jLabel17.setText("Precnik gume");

        jLabel18.setText("Obim gume");

        jLabel19.setText("Broj obrtaja po KM/H");

        jLabel20.setText("Broj obrtaja u sekundi pri 100km/h");

        jLabel21.setText("Razlika visina");

        jLabel22.setText("Brzina");

        brzinaSlovoA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        brzinaSlovoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brzinaSlovoAActionPerformed(evt);
            }
        });

        jLabel23.setText("Broj obrtaja max brzina");

        jLabel24.setText("Razlika brzina");

        indexNosivost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        indexNosivostA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel25.setText("IndeksNosivosti");

        jLabel26.setText("IndeksNosivosti");

        jLabel27.setText("Razlika Nosivosti");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxBrzinaA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxBrzina, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(razlikaBrzina, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel24)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel27)
                                            .addComponent(razlikaNosivost, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(indexNosivost, 0, 120, Short.MAX_VALUE)
                                        .addComponent(indexNosivostA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel26)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(putnickaGuma)
                                        .addGap(18, 18, 18)
                                        .addComponent(teretnaGuma))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel13)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel14))
                            .addComponent(jLabel11))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brzinaSlovoA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel4)
                            .addComponent(brzinaSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(racunanje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(precnikGume, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(obimGume, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(brojKM, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel8)
                                .addComponent(obrtaji, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel16)
                                    .addComponent(precnikGumeA, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(obimGumeA, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(brojKMA, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(obrtajiA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 51, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addComponent(stvarnaV, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(razlikaH))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(putnickaGuma)
                        .addComponent(teretnaGuma)
                        .addComponent(racunanje)
                        .addComponent(jLabel16))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel17))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precnikGume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precnikGumeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(brzinaSlovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(indexNosivost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obimGume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obimGumeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brojKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brojKMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obrtaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obrtajiA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stvarnaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(razlikaH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brzinaSlovoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(indexNosivostA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxBrzina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maxBrzinaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razlikaBrzina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(razlikaNosivost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void putnickaGumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putnickaGumaActionPerformed
        
        if(putnickaGuma.isEnabled())
        {
            okP=true;
            String[] niz = {"12","13","14","15","16","17","18","19","20","21","22",
            "23","24","25","26"};
         ComboBoxModel ppe= new DefaultComboBoxModel( niz );
         jComboBox1.setModel(ppe);
         //////////////////////////////////
         jComboBox1.setVisible(true);
         String[] niz1 = {"145", "155","165","175", "185" ,"195", "205"};
         ComboBoxModel ppe1= new DefaultComboBoxModel( niz1 );
         jComboBox2.setModel(ppe1);
         jComboBox2.setVisible(true);
         ///////////////////////////////////////
         
         String[] niz2={"20","25","30","35","40","45","50","55","60"};
         ComboBoxModel ppe2= new DefaultComboBoxModel( niz2 );
         jComboBox3.setModel(ppe2);
         jComboBox3.setVisible(true);
         //////////////////////////////////////////////////////////////
         
         //String[] niz3 = {"N","P","Q","R","S","T","U","H","V","Z","W","Y"};
         //ComboBoxModel ppe3= new DefaultComboBoxModel( niz3 );
         //jComboBox4.setModel(ppe2);
         //jComboBox4.setVisible(true);
         //int precnik = Integer.parseInt(jComboBox1.getActionCommand());
         //////////////////////////////////////////////////////////////
         String[] niz3 = {"12","13","14","15","16","17","18","19","20","21","22",
            "23","24","25","26"};
         ComboBoxModel ppe3= new DefaultComboBoxModel( niz3 );
         jComboBox7.setModel(ppe3);
         jComboBox7.setVisible(true);
         ////////////////////////////////////////////////
         
         String[] niz4 = { "215", "225", "235", "245", "255", "265", "275", "285", "295", "305", "315", "325", "335", "345", "355"};
         
         ComboBoxModel ppe4= new DefaultComboBoxModel( niz4 );
         jComboBox5.setModel(ppe4);
         jComboBox5.setVisible(true);
         /////////////////////////////////////////////////////////////
         String[] niz5 = {"65", "70", "75", "80", "85", "90"};
         ComboBoxModel ppe5= new DefaultComboBoxModel( niz5 );
         jComboBox6.setModel(ppe5);
         jComboBox6.setVisible(true);
         ////////////////////////////////////////////////////////////
         String[] niz6 = {"N","P","Q","R","S","T","U","H","V","Z","W","Y"};
         ComboBoxModel ppe6= new DefaultComboBoxModel( niz6 );
         brzinaSlovo.setModel(ppe6);
         brzinaSlovo.setVisible(true);
         
         ////////////////////////////////////////////////////////////////
         ComboBoxModel ppe7= new DefaultComboBoxModel( niz6 );
        brzinaSlovoA.setModel(ppe7);
        brzinaSlovoA.setVisible(true);
        /////////////////////////////////////////////////////////////////
        jComboBox1.setSelectedItem(null);
        jComboBox2.setSelectedItem(null);
        jComboBox3.setSelectedItem(null);
        brzinaSlovo.setSelectedItem(null);
        brzinaSlovoA.setSelectedItem(null);
        indexNosivost.setVisible(false);
        indexNosivostA.setVisible(false);
        jComboBox5.setSelectedItem(null);
        jComboBox6.setSelectedItem(null);
        jComboBox7.setSelectedItem(null);
         //jLabel26.setVisible(false);
         //jLabel25.setVisible(false);
        }
        
        
        
    }//GEN-LAST:event_putnickaGumaActionPerformed

    private void teretnaGumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teretnaGumaActionPerformed
        if(teretnaGuma.isEnabled())
        {
            okT = true;
            String[] niz = {"12","13","14","15","16","17","18","19","20","21","22",
            "23","24","25","26"};
         ComboBoxModel ppe= new DefaultComboBoxModel( niz );
         jComboBox1.setModel(ppe);
         jComboBox1.setVisible(true);
         ////////////////////////////////////////////////
         
         String[] niz1 = { "215", "225", "235", "245", "255", "265", "275", "285", "295", "305", "315", "325", "335", "345", "355"};
         
         ComboBoxModel ppe1= new DefaultComboBoxModel( niz1 );
         jComboBox2.setModel(ppe1);
         jComboBox2.setVisible(true);
         /////////////////////////////////////////////////////////////
         String[] niz2 = {"65", "70", "75", "80", "85", "90"};
         ComboBoxModel ppe2= new DefaultComboBoxModel( niz2 );
         jComboBox3.setModel(ppe2);
         jComboBox3.setVisible(true);
         //////////////////////////////////////////////////////////////
         String[] niz3 = {"12","13","14","15","16","17","18","19","20","21","22",
            "23","24","25","26"};
         ComboBoxModel ppe3= new DefaultComboBoxModel( niz3 );
         jComboBox7.setModel(ppe3);
         jComboBox7.setVisible(true);
         ////////////////////////////////////////////////
         
         String[] niz4 = { "215", "225", "235", "245", "255", "265", "275", "285", "295", "305", "315", "325", "335", "345", "355"};
         
         ComboBoxModel ppe4= new DefaultComboBoxModel( niz4 );
         jComboBox5.setModel(ppe4);
         jComboBox5.setVisible(true);
         /////////////////////////////////////////////////////////////
         String[] niz5 = {"65", "70", "75", "80", "85", "90"};
         ComboBoxModel ppe5= new DefaultComboBoxModel( niz5 );
         jComboBox6.setModel(ppe5);
         jComboBox6.setVisible(true);
         ////////////////////////////////////////////////////////////////
         String[] niz6 = {"62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", 
             "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "127"};
         
         ComboBoxModel ppe6= new DefaultComboBoxModel( niz6 );
         indexNosivost.setModel(ppe6);
         indexNosivost.setVisible(true);
         
         ComboBoxModel ppe7= new DefaultComboBoxModel( niz6 );
         indexNosivostA.setModel(ppe7);
         indexNosivostA.setVisible(true);
        //jLabel4.setVisible(false);
        //jLabel22.setVisible(false);
        brzinaSlovo.setVisible(false);
        brzinaSlovoA.setVisible(false); 
        jComboBox1.setSelectedItem(null);
        jComboBox2.setSelectedItem(null);
        jComboBox3.setSelectedItem(null);
        jComboBox5.setSelectedItem(null);
        jComboBox6.setSelectedItem(null);
        jComboBox7.setSelectedItem(null);
        indexNosivost.setSelectedItem(null);
        indexNosivostA.setSelectedItem(null);
         
         }
        
         
    }//GEN-LAST:event_teretnaGumaActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void brzinaSlovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brzinaSlovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brzinaSlovoActionPerformed

    private void racunanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racunanjeActionPerformed
        racunanje.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
             String precnikF = (String)jComboBox1.getSelectedItem();
             String sirinaG = (String)jComboBox2.getSelectedItem();
             String visinaG = (String)jComboBox3.getSelectedItem();
             int precnik = Integer.parseInt(precnikF);
             int sirina = Integer.parseInt(sirinaG);
             int visina = Integer.parseInt(visinaG);
             double precnik1 = Double.parseDouble(precnikF);
             double sirina1 = Double.parseDouble(sirinaG);
             double visina1 = Double.parseDouble(visinaG);
             Tocak tocak = new Tocak(precnik,sirina,visina);
             DecimalFormat df = new DecimalFormat("#.00");
             double precnikT = tocak.precnikGume(precnik1, sirina1, visina1);
             String precnikd = df.format(precnikT);
             precnikGume.setText(precnikd);
             String zObim = precnikGume.getText();
             double obim = Double.parseDouble(zObim);
             double Obim = tocak.obimGume(obim);
             String obimd = df.format(Obim);
             obimGume.setText(obimd);
             String gObim = obimGume.getText();
             double gObim1 = Double.parseDouble(gObim);
             double kMH = tocak.brObrtajaKM(gObim1);
             String kMh = df.format(kMH);
             brojKM.setText(kMh);
             double bObrtaj = tocak.brObrtaja100kmh(gObim1);
             String brojObrtaja = df.format(bObrtaj);
             obrtaji.setText(brojObrtaja);
             //////////////////////////////////////////////////////
             ////////////////ALTERNATIVNA//////////////////////////
             String precnikFA = (String)jComboBox7.getSelectedItem();
             String sirinaGA = (String)jComboBox5.getSelectedItem();
             String visinaGA = (String)jComboBox6.getSelectedItem();
             int precnikA = Integer.parseInt(precnikFA);
             int sirinaA = Integer.parseInt(sirinaGA);
             int visinaA = Integer.parseInt(visinaGA);
             double precnik1A = Double.parseDouble(precnikFA);
             double sirina1A = Double.parseDouble(sirinaGA);
             double visina1A = Double.parseDouble(visinaGA);
             Tocak tocakA = new Tocak(precnikA,sirinaA,visinaA);
             double precnikTA = tocakA.precnikGume(precnik1A, sirina1A, visina1A);
             String precnikdA = df.format(precnikTA);
             precnikGumeA.setText(precnikdA);
             String zObimA = precnikGumeA.getText();
             double obimA = Double.parseDouble(zObimA);
             double ObimA = tocak.obimGume(obimA);
             String obimdA = df.format(ObimA);
             obimGumeA.setText(obimdA);
             String gObimA = obimGumeA.getText();
             double gObim1A = Double.parseDouble(gObimA);
             double kMHA = tocak.brObrtajaKM(gObim1A);
             String kMhA = df.format(kMHA);
             brojKMA.setText(kMhA);
             double bObrtajA = tocakA.brObrtaja100kmh(gObim1A);
             String brojObrtajaA = df.format(bObrtajA);
             obrtajiA.setText(brojObrtajaA);
             double stvarna = tocak.stvarnaBrzina(Obim, ObimA);
             String stvarnaBrzina = df.format(stvarna);
             stvarnaV.setText(stvarnaBrzina);
             double razlika = tocak.razlikaVisine(precnikT, precnikTA);
             String razlikaVisina= df.format(razlika);
             razlikaH.setText(razlikaVisina);
             
             String brzina = (String)brzinaSlovo.getSelectedItem();
             String brzinaA= (String)brzinaSlovoA.getSelectedItem();
             PutnickaGuma pguma = new PutnickaGuma(precnik,sirina,visina,brzina,brzinaA);
             
             double maxV = pguma.brObrtajaMaxBrzina(brzina, Obim);
             String maxBrzinaa = df.format(maxV);
             if (okP==true){maxBrzina.setText(maxBrzinaa);
         
             double maxVA = pguma.brObrtajaMaxBrzina(brzinaA, ObimA);
             String maxBrzinaaA = df.format(maxVA);
             maxBrzinaA.setText(maxBrzinaaA);
             
            double rBrzina = pguma.razlikaBrzina(brzina, brzinaA);
            String razlikaV = String.valueOf(rBrzina);
            razlikaBrzina.setText(razlikaV); 
             razlikaNosivost.setText(null);
             okP=false;
             }
            
            
            
            String index = (String)indexNosivost.getSelectedItem();
            int inDex = Integer.parseInt(index);
            String indexA = (String)indexNosivostA.getSelectedItem();
            int inDexA = Integer.parseInt(indexA);
            TeretnaGuma ttgu = new TeretnaGuma(precnik,sirina,visina,inDex,inDexA);
            int razlikaa = ttgu.razlikaNosivosti(inDex, inDexA);
            String razlikaindex = Integer.toString(razlikaa);
            if(okT==true){razlikaNosivost.setText(razlikaindex);okT=false; maxBrzina.setText("");maxBrzinaA.setText("");razlikaBrzina.setText("");}
            
            /*if (!razlikaindex.equals(null)){maxBrzina.setText("");}
            if (!razlikaindex.equals(null)){maxBrzinaA.setText("");}
            if (!razlikaindex.equals(null)){razlikaBrzina.setText("");}*/
            //razlikaNosivost.setText(null);
            //razlikaindex=null;
            //razlikaBrzina.setText(razlikaindex);
             
             
             
            }
        });

            
    }//GEN-LAST:event_racunanjeActionPerformed

    private void brzinaSlovoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brzinaSlovoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brzinaSlovoAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brojKM;
    private javax.swing.JTextField brojKMA;
    private javax.swing.JComboBox<String> brzinaSlovo;
    private javax.swing.JComboBox<String> brzinaSlovoA;
    private javax.swing.JComboBox<String> indexNosivost;
    private javax.swing.JComboBox<String> indexNosivostA;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField maxBrzina;
    private javax.swing.JTextField maxBrzinaA;
    private javax.swing.JTextField obimGume;
    private javax.swing.JTextField obimGumeA;
    private javax.swing.JTextField obrtaji;
    private javax.swing.JTextField obrtajiA;
    private javax.swing.JTextField precnikGume;
    private javax.swing.JTextField precnikGumeA;
    private javax.swing.JButton putnickaGuma;
    private javax.swing.JButton racunanje;
    private javax.swing.JTextField razlikaBrzina;
    private javax.swing.JTextField razlikaH;
    private javax.swing.JTextField razlikaNosivost;
    private javax.swing.JTextField stvarnaV;
    private javax.swing.JButton teretnaGuma;
    // End of variables declaration//GEN-END:variables
}
